### ISSUE TITLE
Teddy Bear Points Min value doesn't seem to override default of 2000

### ISSUE THREAD

**Issue by ZymoticB** [udacity/virtual-reality-nanodegree-issues#11]
Its seems to me that the value set inside of the Unity inspector for "Teddy Bear Points Min" doesn't override 

```
	[SerializeField]
	private int TeddyBearPointsMin = 2000;
```

If the value is removed 

```
	[SerializeField]
	private int TeddyBearPointsMin;
```

Unity behaves as I would expect. I am running Unity 2017.1.0f3

**Comment by ZymoticB** [comment]
It seems that this value was set this way for the project at the end  but this was confusing during Lesson 6: Hello World as that set the expectation that the bear would drop after spinning the wheel once.

**Comment by martinwilter** [comment]
> Its seems to me that the value set inside of the Unity inspector for "Teddy Bear Points Min" doesn't override
<br>

1. Do you have any steps to reproduce this?
2. Are you on Windows or macOS?

**Comment by martinwilter** [comment]
>It seems that this value was set this way for the project at the end but this was confusing during Lesson 6: Hello World as that set the expectation that the bear would drop after spinning the wheel once.
<br>

The 2,000 points requirement is briefly mentioned a the start of the project lesson:

https://classroom.udacity.com/nanodegrees/nd017/parts/84879677-45a9-436f-ae48-6b520de5055a/modules/66ce6da9-8854-4570-8b9d-570e71b214f5/lessons/511e6177-85ba-4e6a-8eca-edd37423f416/concepts/9c79c0a5-0328-4717-8b7e-5d1fb439f736

But agree, it should also be mentioned in Lesson 6: Hello World.

**Comment by martinwilter** [comment]
Lesson 6: Hello World has been updated according to the suggestion. Thanks for the input, @ZymoticB.

**Comment by ZymoticB** [comment]
Thanks for updating that, it should be clearer now.

I'm unable to reproduce this (including with a fresh copy of the project) so I'm not sure what happened here, I must have misunderstood something. I'm seeing some other odd behaviours but they don't have concrete changes to be made to solve, more general support questions which I assume these issues aren't the right place for. Maybe I'll try the forum

**Comment by martinwilter** [comment]
Sounds good, @ZymoticB. Thanks again for the valuable feedback.
