### ISSUE TITLE
P4 camera movement note

### ISSUE THREAD

**Issue by synthercat** [udacity/virtual-reality-nanodegree-issues#13]
Now that P4 is up to 2017 ver, camera needs to be placed in an empty and that empty into the GameLogic inspector in order for it to move
#p4 #Unity2017

**Comment by durant-udacity** [comment]
We might as well do this and remind students why: it's for GVR Daydream compatibility.

**Comment by martinwilter** [comment]
@synthercat Addendum clarifying video content and pointing out the most critical updates to GVR and Unity has been added to all videos in the [VR Design](https://classroom.udacity.com/nanodegrees/nd017/parts/e9689cfa-b599-4885-bd6f-cce702733878) course. The copy/paste code provided in the lesson nodes  has fixed, cleaned up, and also has more explanatory comments.

Additionally, the starter project has been update with a correctly configured camera rig, and now also includes iTween, updated scripts as well as a Scripts > Solutions folder containing the copy/paste from the lesson.

Thanks for reporting this issue and please let us know if you find anything else in this course.

PS. Full update, including video updates, are in the planning stages.
