### ISSUE TITLE
Immerse Lighting Lesson 7 Quiz Bug

### ISSUE THREAD

**Issue by josephinekao** [udacity/virtual-reality-nanodegree-issues#14]

**Comment by durant-udacity** [comment]
We think this is the classroom link: https://classroom.udacity.com/nanodegrees/nd017/parts/b587c8cc-5053-4385-a669-10e5c02f3b5c/modules/21db6262-b8ae-49de-9a8e-5a728324ca21/lessons/9bc25af8-6042-44b6-aa06-8beb99e25614/concepts/5848a7fd-d264-4377-852d-9690806e207b?contentVersion=3.0.0&contentLocale=en-us
