### ISSUE TITLE
Graphic User Interfaces section missed a detail in the lesson. It doesn't mention needing to add GvrReticlePointer to the camera.

### ISSUE THREAD

**Issue by Marmishurenko** [udacity/virtual-reality-nanodegree-issues#15]

**Comment by martinwilter** [comment]
@Marmishurenko, thanks for reporting. This issue will be fixed alongside #13.

**Comment by martinwilter** [comment]
@Marmishurenko The starter project has been update with a correctly configured camera rig. Please see issue #13 for additional details on this fix.
