### ISSUE TITLE
Incorrect Link in - Protagonist Journey Project

### ISSUE THREAD

**Issue by josephinekao** [udacity/virtual-reality-nanodegree-issues#16]
In the 360 Specialization module, Project: The Protagonist Journey, 2. Build Your Project page, there is an incorrect link. In The Storyboard section, first line, ".....Use either the cross template provided, or the circular....." "cross template" is linked to the wrong file. Currently, the link directs to excel spreadsheet. Instead it should link to the image in Lesson 11: 360 Storyboarding, 3. Pencils at the Ready! page.

**Comment by josephinekao** [comment]
https://udacity.zendesk.com/agent/tickets/572369

**Comment by martinwilter** [comment]
Link has been corrected. Thanks for reporting.
