### ISSUE TITLE
Lesson 13 Project Submission Link Broken

### ISSUE THREAD

**Issue by josephinekao** [udacity/virtual-reality-nanodegree-issues#18]

**Comment by josephinekao** [comment]
"Build an Apartment Project" link in classroom to "How to Submit A Unity Project" (udacityvr.com) is broken


![brokenlink.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b1b871b718f20011415912/125516c66e82c728ace21e0d46ea869528878da586e7b401e81fe086264c22703d46f96925dcb67de616780458574dfe445b5f44fbfdd828f5be3e79984019af80330b2b9b645bf9fa9015ad00bd2a8a4a85b3b8884fc9e93b20e28f9d02.png)

![projects.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b1b871b718f20011415912/125516c66e82c728ace21e0d46f88695298780bd9cabf301b44fff9e2c4533317346f67225d0ba7cbc472c595c0d4baf41585840adfada23a4bf2e6c981e5ab38532022d8c6853beb2901eb70bbb258b4a81b4bf834fc5eb3422f5c6.png)

**Comment by josephinekao** [comment]
https://udacity.zendesk.com/agent/tickets/571267

**Comment by martinwilter** [comment]
Thanks for reporting. This issue has been resolved.
