### ISSUE TITLE
Mobile/360 Specialization Broken Link

### ISSUE THREAD

**Issue by josephinekao** [udacity/virtual-reality-nanodegree-issues#22]
Two students are reporting a link to a repository of videos that produces a dropbox 404 error (Storyteller's Revenge >> Build your own Project). See attached screenshot.

**Comment by josephinekao** [comment]
![Broken Link.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b1b871b718f20011415912/125516c66e82c728ace21e0d46ca869528878de9a3e0b148e611b2843b492d762a10e17132d0ba7dea1b2f020a5846af135d5c44fcfe8d7aa5e53472834e17ff933c0120996048e6edc00db513bb28814e80b6b9834ec4e03d24e38b885d73.jpg)

**Comment by martinwilter** [comment]
[Course 7B Course Assets](https://www.dropbox.com/sh/mttg6ya3dbd2usr/AADpz3nvC826G0KFNDZP6uixa) listed on the [VRND Downloads](http://www.udacityvr.com/downloads) page is also returning 404.

This link can be used until the issue is fixed https://www.dropbox.com/s/t3j9y7xbqcxsn5h/vrnd-c7b-course_materials-001.zip

**Comment by martinwilter** [comment]
This issue has been resolved.

Course assets listed on the [VRND Downloads page](http://www.udacityvr.com/downloads):
https://www.dropbox.com/s/blxm83waen2bvbj/vrnd-c7b-course_materials-001.zip

'giant repository of videos' referenced on the Storyteller's Revenge [Build Your Project page](https://classroom.udacity.com/nanodegrees/nd017/parts/9b102f3e-e80c-42ff-9409-1eaf560758f0/modules/ddc3c7f2-5cb0-48b2-9874-f2c301da6c5d/lessons/e970e8bb-93b6-4dda-aed0-dd26fff9e778/concepts/2b44ef4f-0b4f-4407-95f0-54b44a881a90):
https://www.dropbox.com/sh/gh7ug9hgkf7k7ik/AAAWz0pJ9XvzBub3Dy8ZYXssa

**Comment by martinwilter** [comment]
Daily traffic limit has been exceeded for three days in a row:

>Error (429)
>This link is temporarily disabled. The person who shared it hit their daily limit of traffic or downloads. Learn about traffic limits.

**Comment by martinwilter** [comment]
This issue has been resolved.

Course assets listed on the VRND Downloads page:
https://www.dropbox.com/s/w994mbr5aeu6pam/vrnd-course-7b-course_assets-001.zip

For the 'giant repository of videos' referenced on the Storyteller's Revenge Build Your Project page, some of these are now available on the [VRND Downloads](http://www.udacityvr.com/downloads) page under the 360 Media Repository section.

We will add more footage when possible.
