### ISSUE TITLE
Spatial audio files reported missing Course 7B Course Assets download

### ISSUE THREAD

**Issue by durant-udacity** [udacity/virtual-reality-nanodegree-issues#26]
Course 7B Course Assets (version 1)

on [downloads](https://www.udacityvr.com/downloads/) page

**Comment by durant-udacity** [comment]
Duplicate? #31

**Comment by durant-udacity** [comment]
Also discussed here https://discussions.udacity.com/t/lesson-20-spatial-audio-course-materials-missing/378677

**Comment by martinwilter** [comment]
Issue closed as Duplicate of #31.
