### ISSUE TITLE
Lesson 4.2 Programming Animations

### ISSUE THREAD

**Issue by Spagyria** [udacity/virtual-reality-nanodegree-issues#27]

**Comment by Spagyria** [comment]
The ProgrammingAnimations scene should be moved to the scenes folder. Consistency in naming conventions and asset placement is essential to a smooth work flow. One could argue that I allowed force of habit to direct me to the scenes folder, and the fault lies with me for not seeing the StarterContent folder. But it would have been better to just move that folder into the scenes folder if you wanted the ProgrammingAnimations folder to be segregated from the other scenes.

**Comment by martinwilter** [comment]
Thanks for the feedback, @Spagyria. Currently, because the video shows the ProgrammingAnimations scene  being located inside the StarterContent folder, we feel it's best to leave it there, however, we will keep your feedback in mind for upcoming video updates.
