### ISSUE TITLE
Game Mode Alt doesn't respond (only in GVR 1.6, fixed in GVR 1.7)

### ISSUE THREAD

**Issue by UdacityVM** [udacity/virtual-reality-nanodegree-issues#3]
GVR latest version won't let this happen in PC build settings

**Comment by durant-udacity** [comment]
Upgrading to GVR 1.8 when it's out will be fix this (we'll use it if it's less buggy).

**Comment by martinwilter** [comment]
This issue is related to GVR 1.6 and has been resolved in GVR 1.7.

If using GVR 1.6, switching to iOS or Android platform will activate the game mode camera controls Alt + Move Mouse and Ctrl  + Move Mouse.
