### ISSUE TITLE
Video for "Adding An Open Chest Animation" not available.

### ISSUE THREAD

**Issue by josephinekao** [udacity/virtual-reality-nanodegree-issues#30]
a lesson is missing as it is not available in my content library. It is called "Adding An Open Chest Animation" and is supposed to be right after "Playing with Rays" in Lesson 5: Physics and Audio. Instead, another page showed up with a quiz. The attached image will show the details, I typed "Ready" thinking it will take me to the video but it didn't.

**Comment by josephinekao** [comment]
[Uploading Screenshot (3).png...]

**Comment by josephinekao** [comment]
![Screenshot (3) (1).png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59b1b871b718f20011415912/125516c66e82c728ace21e0d46db978826878dba87e6ab03ec0eb9d461176e316546b3397f8fe62bab0021435a564ba9485c0c11fbf18a79a3b53c708d585aee82655d7dd42103eee9dc4be05ce36ade0d97bcae8b4bcae93825e08c8b46391b0d1e88f94f78.png)

**Comment by martinwilter** [comment]
The lesson node is confusing to some student.  It might need to be clarified that this is an independent exercises where student should use what they have already learned about Animations.
