### ISSUE TITLE
Lesson 1 Downloads Link Issue

### ISSUE THREAD

**Issue by josephinekao** [udacity/virtual-reality-nanodegree-issues#32]
trying to follow Lesson 1 on the VR developer free (I purchased the first term of the VR Nano Degree and I am excited and prepping) but when I was trying to download the associated files (to drop the coconut on the island) it took me to the Nano Degree site instead of taking me to the free VR Developer site. I worked around it, but I want to bring this up as I continue going into the class.

**Comment by martinwilter** [comment]
The course asset download link referenced in the classroom https://classroom.udacity.com/courses/ud1014/lessons/7fbbbe18-db78-4f38-af28-28848959f527/concepts/ec5245bc-cf70-4df4-b12a-d3c4bf3566d4 links to http://www.udacityvr.com/downloads which is a publicly accessible page.
