### ISSUE TITLE
VR Software Development Dead Link

### ISSUE THREAD

**Issue by josephinekao** [udacity/virtual-reality-nanodegree-issues#34]
Reported from student: "I'm working on the VR Nanodegree, section 3 (VR Software Development), Lesson 2 (Controlling Objects Using Code), Section 6 (Creating Objects Using References). I was confused about Quaternions so I clicked on the link that was included on the page with the lesson video. Unfortunately the link is dead, even the top-level domain is no good.Thought I'd throw you a heads-up. Anyway, here's the URL: 
http://blog.preoccupiedgames.com/quaternions-not-satan/"

**Comment by martinwilter** [comment]
Direct link to classroom lesson node: https://classroom.udacity.com/nanodegrees/nd017/parts/c44ecb59-b508-48ab-b43e-29f5240d4563/modules/8d6a5274-0ce3-42b5-b99d-8ff0a9e2646c/lessons/b8c66c9b-5fb2-4385-8042-86a748f12606/concepts/2db5e4fa-ad77-4751-913b-1c24adbc4290
