### ISSUE TITLE
Wrong min API setting

### ISSUE THREAD

**Issue by synthercat** [udacity/virtual-reality-nanodegree-issues#35]
https://classroom.udacity.com/nanodegrees/nd017/parts/84879677-45a9-436f-ae48-6b520de5055a/modules/14690aa7-5124-4d37-a6e0-104c6e812a86/lessons/ef8941d8-7401-41db-bbae-bae7770a3247/concepts/cedccf23-a1d9-4d3f-bec3-0cb2dd6efd65

"For Google Cardboard, you will need to have a version greater than 4.1. Let’s select API 16." should be "For Google Carboard you will need to have at least Android 4.4 - API 19"

**Comment by martinwilter** [comment]
@synthercat Thanks for reporting this and also including specific details. The text has been updated.
