### ISSUE TITLE
VR Software Development Link Dead

### ISSUE THREAD

**Issue by mamademo** [udacity/virtual-reality-nanodegree-issues#36]
Lesson 5: Physics & Audio, section 8: Creating a List. The addendum directs: Learn more about C# arrays: https://msdn.microsoft.com/en-us/library/aa288453(v=vs.71).aspx

The link brings you to Microsoft's Download Center. 

Thanks for your attention to this issue!

**Comment by martinwilter** [comment]
Direct link to classroom lesson node: https://classroom.udacity.com/nanodegrees/nd017/parts/c44ecb59-b508-48ab-b43e-29f5240d4563/modules/8d6a5274-0ce3-42b5-b99d-8ff0a9e2646c/lessons/033b6e5a-6d5b-4ecb-b3f6-e96f891a5059/concepts/a392ac40-c73a-41ad-85bf-4975605a84f5
