### ISSUE TITLE
cannot reach https://udacityvrdeveloper.herokuapp.com/

### ISSUE THREAD

**Issue by utkan** [udacity/virtual-reality-nanodegree-issues#39]
https://udacityvrdeveloper.herokuapp.com/

This page isn’t working

udacityvrdeveloper.herokuapp.com didn’t send any data.
ERR_EMPTY_RESPONSE

**Comment by martinwilter** [comment]
Thanks for reporting this, @utkan.

We are not able to reproduce this error, would you mind trying again? And if you encounter the issue again, share some screenshots with us. Thanks!

**Comment by utkan** [comment]
sorry for bothering you :(
VPN was connected.
After disconnecting, everything is fine.

UTKAN SARGIN
5355047326

**Comment by martinwilter** [comment]
No worries, glad to hear it's working now :)
