### ISSUE TITLE
360 Media Download Issue

### ISSUE THREAD

**Issue by josephinekao** [udacity/virtual-reality-nanodegree-issues#43]

**Comment by josephinekao** [comment]
"In subject 10 - 360 Media Production in lesson 7 'Spatial Audio ' there is information about SpatialAudio directory in course materials, but I am not able to find it. I have downloaded materials once again after contact with my mentor but thee are still only two raw videos and that's all. I think there should be also .pano file which was mentioned earlier in the course but again I could not find it."

**Comment by martinwilter** [comment]
Duplicate of #31.
