### ISSUE TITLE
Broken hyperlink on VRDownload page

### ISSUE THREAD

**Issue by ttakach** [udacity/virtual-reality-nanodegree-issues#50]
VRND DOWNLOADS

http://www.udacityvr.com/downloads

The link to the Unity User Manual regarding "Installing Mulitple Versions of Unity" is broken on the VR Download page.

https://docs.unity3d.com/462/Documentation/Manual/InstallingMultipleVersionsofUnity.html

The unit says this is an important topic, but I am unable to find the document even with a manual search on the Unity site.

**Comment by martinwilter** [comment]
Thanks for reporting this, @ttakach. We have updated the information on www.udacityvr.com/downloads.
