### ISSUE TITLE
Improve Installation Information

### ISSUE THREAD

**Issue by UdacityVM** [udacity/virtual-reality-nanodegree-issues#8]
Add screencasts / animated gifs to instillation instructions for Android or iOS.

**Comment by martinwilter** [comment]
More details has been added to the [Deploying to iOS](https://classroom.udacity.com/nanodegrees/nd017/parts/84879677-45a9-436f-ae48-6b520de5055a/modules/14690aa7-5124-4d37-a6e0-104c6e812a86/lessons/ef8941d8-7401-41db-bbae-bae7770a3247/concepts/2f3b3b70-051c-423f-aa53-91c33fa5a475) lesson node.
